source 'https://rubygems.org'
gem 'rack'
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib'
gem 'sinatra-params'
gem 'sinatra-activerecord'
gem 'mustache-sinatra'
gem 'require_all'
gem 'sqlite3'
gem 'rake'
