source 'https://rubygems.org'
gem 'rack'
gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib'
gem 'sinatra-params'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'activerecord-import'
gem 'liquid'
gem 'mustache-sinatra', require: 'mustache/sinatra'
gem 'will_paginate'
# gem 'ruby-handlebars'
gem 'require_all'
gem 'sqlite3'
gem 'rake'
